import os 
import time

""" GLOBAL FUNCTION """
def Log_Time():
    import datetime
    now = datetime.datetime.now()
    print(now.strftime("%Y-%m-%d %H:%M:%S"))

""" Importing Profiles """
import yaml
from Core.profile import profile_path
profile = open(profile_path)
profile_data = yaml.safe_load(profile)
profile.close()
#Functioning Variables
rhythmbox_client_ControllerTTS_path = profile_data['rhythmbox_client_ControllerTTS_path']
rhythmbox_client_ControllerTTS = rhythmbox_client_ControllerTTS_path + '/SpeechDriver/tts/ServicesTTS/rhythmbox_client_ControllerTTS/'
#print(rhythmbox_client_ControllerTTS)


def toggle(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --play-pause')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: toggle')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    _txt = open('.txt','w+')
    _txt.write(result)
    os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    print(' ')
    _txt = open('.txt','w+')
    _txt.write(result)
    os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    print(' ')

def stop(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --stop')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: stop')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')

def next(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --next')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: next')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')

def previous(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --previous')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: previous')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')


def printplaying(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    import subprocess
    import shlex
    proc = subprocess.Popen(shlex.split('rhythmbox-client --no-start --print-playing-format %tt'))
    title, err = proc.communicate()
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: printplaying')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')

def repeat(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --repeat')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: repeat')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')

def norepeat(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --no-repeat')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: norepeat')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')

def shuffle(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --shuffle')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: shuffle')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')

def noshuffle(accept_path):
    os.system('play ' + accept_path +' &')
    print(' ')
    print(' ')
    time.sleep(1)
    os.system('rhythmbox-client --no-shuffle')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    print(' ')
    print(' ')
    Log_Time()
    print('\t\t\t\tSkill: noshuffle')
    print(' ')
    print(' ')
    print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
    #_txt = open('.txt','w+')
    #_txt.write(result)
    #os.system('gnome-terminal -x python3 ' + rhythmbox_client_ControllerTTS + '__tts.py &')
    #print(' ')

